const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const pool = require('../config/db');
const AdminModel = require('../models/adminModel');
const InternModel = require('../models/internModel');
const OrganizationModel = require('../models/organizationModel');
const emailService = require('../services/emailService');
const { logAudit } = require('../services/auditService');
const {
  signAccessToken,
  generateCsrfToken,
  accessTokenCookieOptions,
  refreshTokenCookieOptions,
  csrfCookieOptions,
} = require('../utils/tokens');
const {
  createSession,
  findSessionByRawToken,
  rotateSession,
  revokeSessionByRawToken,
  revokeAllSessionsForActor,
  blacklistJti,
} = require('../services/sessionService');
const { CONSENT_VERSION } = require('../config/consent');

// True if this intern still needs to see the consent notice — either they
// never accepted one, or they accepted an older policy version than what's
// currently in force.
const internNeedsConsent = (intern) => intern.consent_version !== CONSENT_VERSION;

// Issues a brand-new session (fresh refresh token) and sets all three auth
// cookies. Used on login/signup/internLogin — refresh uses its own rotation
// path instead (see `refresh` below) so an old session row is provably
// retired rather than silently reused.
const issueNewSession = async (res, req, { id, role, organizationId }) => {
  const { token: accessToken } = signAccessToken({ id, role, organizationId });
  const refreshRaw = await createSession({
    actorId: id,
    actorRole: role,
    userAgent: req.headers['user-agent'],
    ip: req.ip,
  });
  const csrfToken = generateCsrfToken();
  setAuthCookies(res, { accessToken, refreshRaw, csrfToken });
};

const setAuthCookies = (res, { accessToken, refreshRaw, csrfToken }) => {
  res.cookie('access_token', accessToken, accessTokenCookieOptions());
  res.cookie('refresh_token', refreshRaw, refreshTokenCookieOptions());
  res.cookie('csrf_token', csrfToken, csrfCookieOptions());
};

const clearAuthCookies = (res) => {
  res.clearCookie('access_token', { path: '/' });
  res.clearCookie('refresh_token', { path: '/api/auth' });
  res.clearCookie('csrf_token', { path: '/' });
};

const signup = async (req, res, next) => {
  const client = await pool.connect();
  try {
    const { name, email, password, signup_key, organization_name, invite_code } = req.body;

    // Two ways to become an admin: (1) the global ADMIN_SIGNUP_KEY, which
    // creates a brand-new organization, or (2) an invite_code generated by
    // an existing admin from their Settings page, which joins that admin's
    // existing organization as a second admin instead. Exactly one of these
    // paths is required -- an invite code already proves an existing admin
    // vouched for this signup, so the global key isn't also required.
    let organization = null;
    if (invite_code && String(invite_code).trim()) {
      organization = await OrganizationModel.findByInviteCode(String(invite_code).trim());
      if (!organization) {
        return res.status(403).json({ success: false, message: 'Invalid or expired invite code.' });
      }
    } else if (signup_key !== process.env.ADMIN_SIGNUP_KEY) {
      return res.status(403).json({ success: false, message: 'Invalid signup key. Contact your system administrator.' });
    }

    if (!name || !email || !password) {
      return res.status(400).json({ success: false, message: 'All fields are required' });
    }

    if (password.length < 6) {
      return res.status(400).json({ success: false, message: 'Password must be at least 6 characters' });
    }

    // Email is globally unique across all orgs (see design decision — no
    // per-org uniqueness, no workspace picker at login).
    const exists = await AdminModel.findByEmail(email);
    if (exists) {
      return res.status(400).json({ success: false, message: 'Email already registered' });
    }

    await client.query('BEGIN');

    if (!organization) {
      const orgResult = await client.query(
        `INSERT INTO organizations (name) VALUES ($1) RETURNING *`,
        [organization_name || `${name}'s Organization`]
      );
      organization = orgResult.rows[0];
    }

    const hashed = await bcrypt.hash(password, 10);
    const adminResult = await client.query(
      `INSERT INTO admins (name, email, password, organization_id)
       VALUES ($1, $2, $3, $4) RETURNING id, name, email, organization_id, created_at`,
      [name, email, hashed, organization.id]
    );
    const admin = adminResult.rows[0];

    await client.query('COMMIT');

    logAudit({
      organizationId: admin.organization_id, actorId: admin.id, actorRole: 'admin', action: 'create',
      entityType: 'admin', entityId: admin.id,
      changedFields: { name: admin.name, email: admin.email, via_invite_code: !!invite_code },
    });

    await emailService.sendAdminWelcome({ name: admin.name, email: admin.email }).catch(() => {});

    await issueNewSession(res, req, { id: admin.id, role: 'admin', organizationId: admin.organization_id });

    res.status(201).json({ success: true, data: { admin } });
  } catch (err) {
    await client.query('ROLLBACK');
    next(err);
  } finally {
    client.release();
  }
};

const login = async (req, res, next) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'Email and password are required' });
    }

    const admin = await AdminModel.findByEmail(email);
    if (!admin) {
      return res.status(401).json({ success: false, message: 'Invalid credentials' });
    }

    const valid = await AdminModel.verifyPassword(password, admin.password);
    if (!valid) {
      return res.status(401).json({ success: false, message: 'Invalid credentials' });
    }

    await issueNewSession(res, req, { id: admin.id, role: 'admin', organizationId: admin.organization_id });

    res.json({
      success: true,
      data: {
        admin: { id: admin.id, name: admin.name, email: admin.email, organization_id: admin.organization_id },
      },
    });
  } catch (err) { next(err); }
};

const internLogin = async (req, res, next) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ success: false, message: 'Email and password required' });
    }

    const intern = await InternModel.findByEmail(email);
    if (!intern || !intern.password) {
      return res.status(401).json({ success: false, message: 'Invalid credentials' });
    }

    const valid = await bcrypt.compare(password, intern.password);
    if (!valid) {
      return res.status(401).json({ success: false, message: 'Invalid credentials' });
    }

    await issueNewSession(res, req, { id: intern.id, role: 'intern', organizationId: intern.organization_id });

    res.json({
      success: true,
      data: {
        intern: {
          id: intern.id, name: intern.name, email: intern.email, department: intern.department, organization_id: intern.organization_id,
          needs_consent: internNeedsConsent(intern),
        },
      },
    });
  } catch (err) { next(err); }
};

// Who-am-I check — the frontend calls this on load since it can no longer
// read the (HttpOnly) access token itself to know if a session exists.
// Reads fresh from the DB (org-scoped, per role) rather than trusting the
// JWT payload verbatim, so a deactivated/deleted/moved-org account doesn't
// keep showing as logged in until the access token's natural 15min expiry.
const me = async (req, res, next) => {
  try {
    const orgId = req.user.organization_id;
    if (req.user.role === 'admin') {
      const admin = await AdminModel.getById(orgId, req.user.id);
      if (!admin) return res.status(401).json({ success: false, message: 'Unauthorized' });
      return res.json({ success: true, data: { role: 'admin', admin } });
    }
    if (req.user.role === 'intern') {
      const intern = await InternModel.getById(orgId, req.user.id);
      if (!intern) return res.status(401).json({ success: false, message: 'Unauthorized' });
      return res.json({
        success: true,
        data: {
          role: 'intern',
          intern: {
            id: intern.id, name: intern.name, email: intern.email, department: intern.department, organization_id: intern.organization_id,
            needs_consent: internNeedsConsent(intern),
          },
        },
      });
    }
    res.status(401).json({ success: false, message: 'Unauthorized' });
  } catch (err) { next(err); }
};

// Rotates a refresh token: the presented raw token is looked up regardless
// of its current status so reuse of an already-rotated (revoked) token can
// be detected and treated as a compromise signal, not just an expiry.
const refresh = async (req, res, next) => {
  try {
    const raw = req.cookies?.refresh_token;
    if (!raw) return res.status(401).json({ success: false, message: 'No refresh token' });

    const session = await findSessionByRawToken(raw);
    if (!session) {
      clearAuthCookies(res);
      return res.status(401).json({ success: false, message: 'Invalid session' });
    }

    const expired = new Date(session.expires_at) < new Date();
    if (session.revoked_at || expired) {
      if (session.revoked_at && !expired) {
        // This exact refresh token was already used once and is being
        // replayed — most likely a stolen cookie. Kill every session for
        // this actor rather than just this one, and force a fresh login.
        await revokeAllSessionsForActor(session.actor_id, session.actor_role);
      }
      clearAuthCookies(res);
      return res.status(401).json({ success: false, message: 'Session expired or revoked. Please log in again.' });
    }

    // organization_id isn't stored on the session row — fetched fresh here
    // (not carried over from any prior token) so a since-changed org
    // membership can't be replayed via an old refresh token.
    let organizationId;
    if (session.actor_role === 'admin') {
      const r = await pool.query('SELECT organization_id FROM admins WHERE id = $1', [session.actor_id]);
      organizationId = r.rows[0]?.organization_id;
    } else if (session.actor_role === 'intern') {
      const r = await pool.query('SELECT organization_id FROM interns WHERE id = $1 AND deleted_at IS NULL', [session.actor_id]);
      organizationId = r.rows[0]?.organization_id;
    }
    if (!organizationId) {
      await revokeSessionByRawToken(raw);
      clearAuthCookies(res);
      return res.status(401).json({ success: false, message: 'Account no longer active. Please log in again.' });
    }

    const refreshRaw = await rotateSession(session);
    const { token: accessToken } = signAccessToken({ id: session.actor_id, role: session.actor_role, organizationId });
    const csrfToken = generateCsrfToken();
    setAuthCookies(res, { accessToken, refreshRaw, csrfToken });

    res.json({ success: true });
  } catch (err) { next(err); }
};

const logout = async (req, res, next) => {
  try {
    const accessToken = req.cookies?.access_token;
    if (accessToken) {
      // Decode only (no verify) — an expired/borderline-invalid access
      // token should still let logout clean up the refresh session below;
      // blacklisting is best-effort bookkeeping, not the source of truth.
      const decoded = jwt.decode(accessToken);
      if (decoded?.jti && decoded?.exp) {
        await blacklistJti(decoded.jti, new Date(decoded.exp * 1000));
      }
    }

    const refreshRaw = req.cookies?.refresh_token;
    if (refreshRaw) {
      await revokeSessionByRawToken(refreshRaw);
    }

    clearAuthCookies(res);
    res.json({ success: true, message: 'Logged out' });
  } catch (err) { next(err); }
};

module.exports = { signup, login, me, internLogin, refresh, logout };
